#!/usr/bin/env python3
"""
CorX Labs — model catalogue for /benchmarks/.

The single source of truth behind every generated page and behind
assets/data/models.json.

PROVENANCE RULE
---------------
Every number in here is a *published* figure — taken from a model card, a
system card, a release post, a technical report, or a public leaderboard.
CorX Labs has not re-run these evaluations.

If a figure is not known with confidence it is left as None, and the site
renders it as "Not reported". Guessing a plausible-looking score would make
this catalogue worse than useless, so it is never done. `verified` on each
model records when its row was last checked against sources.
"""

# ---------------------------------------------------------------------------
# Companies
#
# `color` is used for the monogram tile only — it is a legibility choice, not
# a claim about a brand's official palette.
# ---------------------------------------------------------------------------
COMPANIES = {
    "openai":     {"name": "OpenAI",          "country": "United States", "site": "openai.com",       "color": "#0d0d0d"},
    "anthropic":  {"name": "Anthropic",       "country": "United States", "site": "anthropic.com",    "color": "#c15f3c"},
    "google":     {"name": "Google DeepMind", "country": "United States", "site": "deepmind.google",  "color": "#1a73e8"},
    "meta":       {"name": "Meta AI",         "country": "United States", "site": "ai.meta.com",      "color": "#0064e0"},
    "mistral":    {"name": "Mistral AI",      "country": "France",        "site": "mistral.ai",       "color": "#fa520f"},
    "deepseek":   {"name": "DeepSeek",        "country": "China",         "site": "deepseek.com",     "color": "#4d6bfe"},
    "alibaba":    {"name": "Alibaba Qwen",    "country": "China",         "site": "qwen.ai",          "color": "#615ced"},
    "xai":        {"name": "xAI",             "country": "United States", "site": "x.ai",             "color": "#0d0d0d"},
    "amazon":     {"name": "Amazon",          "country": "United States", "site": "aws.amazon.com",   "color": "#ff9900"},
    "microsoft":  {"name": "Microsoft",       "country": "United States", "site": "microsoft.com",    "color": "#0078d4"},
    "cohere":     {"name": "Cohere",          "country": "Canada",        "site": "cohere.com",       "color": "#d18ee2"},
    "ai21":       {"name": "AI21 Labs",       "country": "Israel",        "site": "ai21.com",         "color": "#e8446e"},
    "moonshot":   {"name": "Moonshot AI",     "country": "China",         "site": "moonshot.ai",      "color": "#1f1f1f"},
    "zai":        {"name": "Z.ai (Zhipu)",    "country": "China",         "site": "z.ai",             "color": "#3859ff"},
    "minimax":    {"name": "MiniMax",         "country": "China",         "site": "minimax.io",       "color": "#e8452c"},
    "nvidia":     {"name": "NVIDIA",          "country": "United States", "site": "nvidia.com",       "color": "#76b900"},
    "allenai":    {"name": "Allen Institute", "country": "United States", "site": "allenai.org",      "color": "#0fcb8c"},
    "01ai":       {"name": "01.AI",           "country": "China",         "site": "01.ai",            "color": "#003425"},
    "reka":       {"name": "Reka AI",         "country": "United States", "site": "reka.ai",          "color": "#ff5c39"},
    "liquid":     {"name": "Liquid AI",       "country": "United States", "site": "liquid.ai",        "color": "#1a1a1a"},
    "perplexity": {"name": "Perplexity",      "country": "United States", "site": "perplexity.ai",    "color": "#20808d"},
    "baidu":      {"name": "Baidu",           "country": "China",         "site": "baidu.com",        "color": "#2932e1"},
    "tencent":    {"name": "Tencent",         "country": "China",         "site": "hunyuan.tencent.com", "color": "#0052d9"},
    "bytedance":  {"name": "ByteDance Seed",  "country": "China",         "site": "seed.bytedance.com",  "color": "#325ab4"},
    "stepfun":    {"name": "StepFun",         "country": "China",         "site": "stepfun.com",      "color": "#1c64f2"},
    "ibm":        {"name": "IBM",             "country": "United States", "site": "ibm.com",          "color": "#0f62fe"},
    "databricks": {"name": "Databricks",      "country": "United States", "site": "databricks.com",   "color": "#ff3621"},
    "nous":       {"name": "Nous Research",   "country": "United States", "site": "nousresearch.com", "color": "#4a4a4a"},
    "upstage":    {"name": "Upstage",         "country": "South Korea",   "site": "upstage.ai",       "color": "#8a3ffc"},
    "inception":  {"name": "Inception Labs",  "country": "United States", "site": "inceptionlabs.ai", "color": "#6b46c1"},
    "tii":        {"name": "TII Falcon",      "country": "UAE",           "site": "falconllm.tii.ae", "color": "#1f4e79"},
    "salesforce": {"name": "Salesforce AI",   "country": "United States", "site": "salesforce.com",   "color": "#00a1e0"},
    "snowflake":  {"name": "Snowflake",       "country": "United States", "site": "snowflake.com",    "color": "#29b5e8"},
    "writer":     {"name": "Writer",          "country": "United States", "site": "writer.com",       "color": "#5a3fff"},
    "lgai":       {"name": "LG AI Research",  "country": "South Korea",   "site": "lgresearch.ai",    "color": "#a50034"},
    "naver":      {"name": "Naver",           "country": "South Korea",   "site": "clova.ai",         "color": "#03c75a"},
    "sarvam":     {"name": "Sarvam AI",       "country": "India",         "site": "sarvam.ai",        "color": "#f05a28"},
    "inclusion":  {"name": "InclusionAI (Ant)", "country": "China",       "site": "inclusionai.org",  "color": "#1677ff"},
    "openbmb":    {"name": "OpenBMB",         "country": "China",         "site": "openbmb.cn",       "color": "#2f6feb"},
    "rednote":    {"name": "RedNote (Xiaohongshu)", "country": "China",   "site": "xiaohongshu.com",  "color": "#ff2442"},
    "apple":      {"name": "Apple",           "country": "United States", "site": "apple.com",        "color": "#555555"},
    "corx":       {"name": "CorX Labs",       "country": "Jamaica",       "site": "corx-labs.com",    "color": "#3d3025"},
}

# ---------------------------------------------------------------------------
# Benchmarks
#
# `higher` is always True here — every metric below is "bigger is better".
# `unit` drives formatting: "pct" renders 88.4 as 88.4%, "elo" renders raw.
# ---------------------------------------------------------------------------
BENCHMARKS = [
    {"key": "mmlu_pro", "name": "MMLU-Pro", "unit": "pct", "group": "Knowledge",
     "blurb": "12,000 reasoning-heavy multiple-choice questions across 14 academic "
              "subjects, with ten options instead of four. The harder successor to MMLU.",
     "url": "https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro"},
    {"key": "gpqa", "name": "GPQA Diamond", "unit": "pct", "group": "Reasoning",
     "blurb": "198 graduate-level physics, chemistry and biology questions written to be "
              "Google-proof. PhD holders in the matching field score about 65%.",
     "url": "https://arxiv.org/abs/2311.12022"},
    {"key": "aime", "name": "AIME 2025", "unit": "pct", "group": "Maths",
     "blurb": "The American Invitational Mathematics Examination — 15 problems, integer "
              "answers, no partial credit. A standard test of multi-step maths reasoning.",
     "url": "https://artofproblemsolving.com/wiki/index.php/AIME_Problems_and_Solutions"},
    {"key": "math", "name": "MATH-500", "unit": "pct", "group": "Maths",
     "blurb": "500 competition maths problems sampled from the MATH benchmark, graded on "
              "the final answer.",
     "url": "https://github.com/openai/prm800k"},
    {"key": "swe", "name": "SWE-bench Verified", "unit": "pct", "group": "Coding",
     "blurb": "500 human-validated GitHub issues from real Python repositories. The model "
              "must produce a patch that makes the project's own tests pass.",
     "url": "https://openai.com/index/introducing-swe-bench-verified/"},
    {"key": "lcb", "name": "LiveCodeBench", "unit": "pct", "group": "Coding",
     "blurb": "Competitive-programming problems collected after each model's training "
              "cutoff, so contamination cannot inflate the score.",
     "url": "https://livecodebench.github.io/"},
    {"key": "humaneval", "name": "HumanEval", "unit": "pct", "group": "Coding",
     "blurb": "164 short Python functions written from a docstring. Saturated at the "
              "frontier — kept here for continuity with older models.",
     "url": "https://github.com/openai/human-eval"},
    {"key": "mmmu", "name": "MMMU", "unit": "pct", "group": "Multimodal",
     "blurb": "College-level questions that require reading charts, diagrams, tables and "
              "photographs alongside the text.",
     "url": "https://mmmu-benchmark.github.io/"},
    {"key": "ifeval", "name": "IFEval", "unit": "pct", "group": "Instruction following",
     "blurb": "Verifiable instructions — word counts, formats, forbidden words — checked "
              "by a program rather than a judge model.",
     "url": "https://arxiv.org/abs/2311.07911"},
    {"key": "arena", "name": "LMArena Elo", "unit": "elo", "group": "Human preference",
     "blurb": "Elo rating from blind pairwise votes by the public on LMArena. Measures "
              "what people prefer, not what is correct.",
     "url": "https://lmarena.ai/leaderboard"},
]

BENCH_BY_KEY = {b["key"]: b for b in BENCHMARKS}


def M(slug, name, company, **kw):
    """One model row. Unknown fields stay absent and render as 'Not reported'."""
    row = {"slug": slug, "name": name, "company": company}
    row.update(kw)
    return row


# ---------------------------------------------------------------------------
# Models
#
# ctx / out are token counts. pin / pout are USD per million tokens on the
# vendor's own first-party API at standard (non-batch) rates. Open-weight
# models priced here reflect a representative hosted provider and are marked
# `hosted_price: True`, because the weights themselves are free.
# ---------------------------------------------------------------------------
MODELS = [

    # ---------------------------------------------------------------- OpenAI
    M("gpt-5", "GPT-5", "openai", rel="2025-08", arch="MoE", ctx=400000, out=128000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=1.25, pout=10.0, pcache=0.125, reason=True, tools=True, cut="2024-09",
      desc="OpenAI's flagship reasoning model, with an adjustable thinking budget that "
           "routes easy prompts to a fast path and hard ones to extended reasoning.",
      b={"gpqa": 85.7, "aime": 94.6, "swe": 74.9, "mmmu": 84.2},
      verified="2026-08"),
    M("gpt-5-mini", "GPT-5 mini", "openai", rel="2025-08", arch="MoE", ctx=400000, out=128000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.25, pout=2.0, pcache=0.025, reason=True, tools=True, cut="2024-05",
      desc="A cheaper GPT-5 tuned for well-defined tasks — the default choice when the "
           "prompt is clear and the volume is high.",
      b={"gpqa": 82.3, "aime": 91.1, "swe": 71.0},
      verified="2026-08"),
    M("gpt-5-nano", "GPT-5 nano", "openai", rel="2025-08", arch="MoE", ctx=400000, out=128000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.05, pout=0.40, pcache=0.005, reason=True, tools=True, cut="2024-05",
      desc="The smallest GPT-5, priced for classification, extraction and routing rather "
           "than open-ended reasoning.",
      b={"gpqa": 71.2, "aime": 85.2},
      verified="2026-08"),
    M("o3", "o3", "openai", rel="2025-04", ctx=200000, out=100000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=8.0, pcache=0.5, reason=True, tools=True, cut="2024-06",
      desc="The reasoning model that preceded GPT-5, and the first to use tools inside "
           "its own chain of thought.",
      b={"gpqa": 83.3, "aime": 88.9, "swe": 69.1, "mmmu": 82.9},
      verified="2026-08"),
    M("o4-mini", "o4-mini", "openai", rel="2025-04", ctx=200000, out=100000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=1.10, pout=4.40, pcache=0.275, reason=True, tools=True, cut="2024-06",
      desc="A small reasoning model that punches far above its price on maths and code.",
      b={"gpqa": 81.4, "aime": 92.7, "swe": 68.1, "mmmu": 81.6},
      verified="2026-08"),
    M("o3-mini", "o3-mini", "openai", rel="2025-01", ctx=200000, out=100000,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=1.10, pout=4.40, reason=True, tools=True, cut="2023-10",
      desc="The first cheap reasoning model, with selectable low/medium/high effort.",
      b={"gpqa": 79.7, "aime": 87.3, "swe": 49.3},
      verified="2026-08"),
    M("o1", "o1", "openai", rel="2024-12", ctx=200000, out=100000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=15.0, pout=60.0, reason=True, tools=True, cut="2023-10",
      desc="The model that introduced inference-time reasoning to a mainstream API.",
      b={"gpqa": 78.0, "aime": 79.2, "swe": 48.9, "mmmu": 77.3},
      verified="2026-08"),
    M("gpt-4-1", "GPT-4.1", "openai", rel="2025-04", ctx=1047576, out=32768,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=8.0, pcache=0.5, reason=False, tools=True, cut="2024-06",
      desc="A million-token non-reasoning model built for long-context retrieval and "
           "instruction following.",
      b={"mmlu_pro": 80.5, "gpqa": 66.3, "swe": 54.6, "mmmu": 74.8, "ifeval": 87.4},
      verified="2026-08"),
    M("gpt-4-1-mini", "GPT-4.1 mini", "openai", rel="2025-04", ctx=1047576, out=32768,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.40, pout=1.60, pcache=0.10, reason=False, tools=True, cut="2024-06",
      desc="Most of GPT-4.1's behaviour at a fifth of the price, same million-token window.",
      b={"gpqa": 65.0, "swe": 23.6, "mmmu": 72.7},
      verified="2026-08"),
    M("gpt-4-1-nano", "GPT-4.1 nano", "openai", rel="2025-04", ctx=1047576, out=32768,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.10, pout=0.40, pcache=0.025, reason=False, tools=True, cut="2024-06",
      desc="OpenAI's cheapest million-token model — autocomplete, tagging and routing.",
      b={"gpqa": 50.3, "mmmu": 55.4},
      verified="2026-08"),
    M("gpt-4o", "GPT-4o", "openai", rel="2024-05", ctx=128000, out=16384,
      inp=["text", "image", "audio"], outp=["text"], lic="Proprietary", open=False,
      pin=2.50, pout=10.0, pcache=1.25, reason=False, tools=True, cut="2023-10",
      desc="The natively multimodal model that set the price floor for frontier chat in 2024.",
      b={"mmlu_pro": 74.7, "gpqa": 53.6, "humaneval": 90.2, "mmmu": 69.1, "arena": 1285},
      verified="2026-08"),
    M("gpt-4o-mini", "GPT-4o mini", "openai", rel="2024-07", ctx=128000, out=16384,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.15, pout=0.60, pcache=0.075, reason=False, tools=True, cut="2023-10",
      desc="For two years the default cheap model for high-volume production work.",
      b={"mmlu_pro": 63.1, "gpqa": 40.2, "humaneval": 87.2, "mmmu": 59.4},
      verified="2026-08"),
    M("gpt-oss-120b", "gpt-oss-120b", "openai", rel="2025-08", arch="MoE", params="117B",
      active="5.1B", ctx=131072, out=131072, inp=["text"], outp=["text"],
      lic="Apache 2.0", open=True, hosted_price=True, pin=0.10, pout=0.50,
      reason=True, tools=True, hf="openai/gpt-oss-120b",
      desc="OpenAI's first open-weight release since GPT-2 — a sparse mixture of experts "
           "that fits on a single 80GB accelerator.",
      b={"gpqa": 80.1, "aime": 92.5, "mmlu_pro": 80.9},
      verified="2026-08"),
    M("gpt-oss-20b", "gpt-oss-20b", "openai", rel="2025-08", arch="MoE", params="21B",
      active="3.6B", ctx=131072, out=131072, inp=["text"], outp=["text"],
      lic="Apache 2.0", open=True, hosted_price=True, pin=0.05, pout=0.20,
      reason=True, tools=True, hf="openai/gpt-oss-20b",
      desc="The small open-weight sibling — designed to run on a 16GB consumer GPU.",
      b={"gpqa": 71.5, "aime": 90.0, "mmlu_pro": 73.2},
      verified="2026-08"),

    # ------------------------------------------------------------- Anthropic
    M("claude-opus-4-5", "Claude Opus 4.5", "anthropic", rel="2025-11", ctx=200000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=5.0, pout=25.0, pcache=0.50, reason=True, tools=True, cut="2025-03",
      desc="Anthropic's most capable model, and the first Opus priced within reach of "
           "everyday production use.",
      b={"swe": 80.9, "gpqa": 87.0, "aime": 96.0, "mmmu": 82.0},
      verified="2026-08"),
    M("claude-sonnet-4-5", "Claude Sonnet 4.5", "anthropic", rel="2025-09", ctx=1000000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, pcache=0.30, reason=True, tools=True, cut="2025-01",
      desc="The workhorse of the Claude 4.5 family — strongest of its generation at "
           "long-running agentic coding, with a million-token window in beta.",
      b={"swe": 77.2, "gpqa": 83.4, "aime": 87.0, "mmmu": 77.8},
      verified="2026-08"),
    M("claude-haiku-4-5", "Claude Haiku 4.5", "anthropic", rel="2025-10", ctx=200000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=1.0, pout=5.0, pcache=0.10, reason=True, tools=True, cut="2025-02",
      desc="Near-Sonnet-4 coding ability at a third of the price and roughly twice the speed.",
      b={"swe": 73.3, "gpqa": 73.0, "aime": 77.0},
      verified="2026-08"),
    M("claude-opus-4-1", "Claude Opus 4.1", "anthropic", rel="2025-08", ctx=200000, out=32000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=15.0, pout=75.0, pcache=1.50, reason=True, tools=True, cut="2025-01",
      desc="An incremental upgrade to Opus 4 focused on multi-file refactoring accuracy.",
      b={"swe": 74.5, "gpqa": 80.9, "aime": 78.0},
      verified="2026-08"),
    M("claude-sonnet-4", "Claude Sonnet 4", "anthropic", rel="2025-05", ctx=200000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, pcache=0.30, reason=True, tools=True, cut="2025-01",
      desc="The first Claude with a hybrid instant/extended-thinking switch in the API.",
      b={"swe": 72.7, "gpqa": 75.4, "aime": 70.5, "mmmu": 74.4},
      verified="2026-08"),
    M("claude-3-7-sonnet", "Claude 3.7 Sonnet", "anthropic", rel="2025-02", ctx=200000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, reason=True, tools=True, cut="2024-10",
      desc="The bridge release that introduced visible extended thinking to Claude.",
      b={"swe": 62.3, "gpqa": 68.0, "aime": 61.3, "mmmu": 71.8},
      verified="2026-08"),
    M("claude-3-5-sonnet", "Claude 3.5 Sonnet", "anthropic", rel="2024-10", ctx=200000, out=8192,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, reason=False, tools=True, cut="2024-04",
      desc="The 2024 coding benchmark other labs measured themselves against.",
      b={"mmlu_pro": 78.0, "gpqa": 65.0, "humaneval": 93.7, "swe": 49.0, "mmmu": 70.4, "arena": 1268},
      verified="2026-08"),
    M("claude-3-5-haiku", "Claude 3.5 Haiku", "anthropic", rel="2024-11", ctx=200000, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.80, pout=4.0, reason=False, tools=True, cut="2024-07",
      desc="A fast, cheap Claude that matched the previous generation's flagship on code.",
      b={"mmlu_pro": 65.0, "gpqa": 41.6, "humaneval": 88.1, "swe": 40.6},
      verified="2026-08"),
    M("claude-3-opus", "Claude 3 Opus", "anthropic", rel="2024-03", ctx=200000, out=4096,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=15.0, pout=75.0, reason=False, tools=True, cut="2023-08",
      desc="The first Claude to trade blows with GPT-4, and still prized for prose.",
      b={"mmlu_pro": 68.5, "gpqa": 50.4, "humaneval": 84.9, "mmmu": 59.4, "arena": 1247},
      verified="2026-08"),

    # ---------------------------------------------------------------- Google
    M("gemini-3-pro", "Gemini 3 Pro", "google", rel="2025-11", ctx=1048576, out=65536,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=12.0, pcache=0.20, reason=True, tools=True, cut="2025-01",
      desc="Google's frontier model — a million-token window that natively ingests video "
           "and audio, not just text and stills.",
      b={"gpqa": 91.9, "aime": 95.0, "swe": 76.2, "mmmu": 81.0},
      verified="2026-08"),
    M("gemini-2-5-pro", "Gemini 2.5 Pro", "google", rel="2025-03", ctx=1048576, out=65536,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=1.25, pout=10.0, pcache=0.31, reason=True, tools=True, cut="2025-01",
      desc="The first Gemini with reasoning on by default, and a long run at the top of "
           "the public preference leaderboards.",
      b={"gpqa": 84.0, "aime": 86.7, "swe": 63.8, "mmmu": 81.7, "arena": 1439},
      verified="2026-08"),
    M("gemini-2-5-flash", "Gemini 2.5 Flash", "google", rel="2025-04", ctx=1048576, out=65536,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=0.30, pout=2.50, pcache=0.075, reason=True, tools=True, cut="2025-01",
      desc="A thinking model with a budget dial you set per request — including zero.",
      b={"gpqa": 78.3, "aime": 78.0, "mmmu": 79.7, "arena": 1393},
      verified="2026-08"),
    M("gemini-2-5-flash-lite", "Gemini 2.5 Flash-Lite", "google", rel="2025-06", ctx=1048576,
      out=65536, inp=["text", "image", "audio", "video"], outp=["text"],
      lic="Proprietary", open=False, pin=0.10, pout=0.40, reason=True, tools=True, cut="2025-01",
      desc="Google's cheapest million-token model, aimed at classification and summarisation.",
      b={"gpqa": 64.6, "aime": 49.8},
      verified="2026-08"),
    M("gemini-2-0-flash", "Gemini 2.0 Flash", "google", rel="2025-01", ctx=1048576, out=8192,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=0.10, pout=0.40, reason=False, tools=True, cut="2024-08",
      desc="The generation that made million-token context ordinary rather than premium.",
      b={"mmlu_pro": 77.6, "gpqa": 62.1, "mmmu": 71.7, "arena": 1356},
      verified="2026-08"),
    M("gemini-1-5-pro", "Gemini 1.5 Pro", "google", rel="2024-05", ctx=2097152, out=8192,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=1.25, pout=5.0, reason=False, tools=True, cut="2023-11",
      desc="The two-million-token model that proved long context could work in production.",
      b={"mmlu_pro": 75.8, "gpqa": 59.1, "humaneval": 84.1, "mmmu": 62.2},
      verified="2026-08"),
    M("gemma-3-27b", "Gemma 3 27B", "google", rel="2025-03", params="27B", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Gemma Terms of Use", open=True,
      hosted_price=True, pin=0.10, pout=0.20, reason=False, tools=True,
      hf="google/gemma-3-27b-it",
      desc="Google's open-weight flagship — multimodal, 140 languages, one GPU.",
      b={"mmlu_pro": 67.5, "gpqa": 42.4, "humaneval": 87.8, "mmmu": 64.9, "arena": 1338},
      verified="2026-08"),
    M("gemma-3-12b", "Gemma 3 12B", "google", rel="2025-03", params="12B", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Gemma Terms of Use", open=True,
      hosted_price=True, pin=0.05, pout=0.10, reason=False, tools=True,
      hf="google/gemma-3-12b-it",
      desc="The mid-size Gemma 3 — the usual pick for a 24GB card.",
      b={"mmlu_pro": 60.6, "gpqa": 34.9, "mmmu": 59.6},
      verified="2026-08"),
    M("gemma-3-4b", "Gemma 3 4B", "google", rel="2025-03", params="4B", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Gemma Terms of Use", open=True,
      hosted_price=True, pin=0.02, pout=0.04, reason=False, tools=True,
      hf="google/gemma-3-4b-it",
      desc="Small enough for a laptop, still multimodal and 128k-context.",
      b={"mmlu_pro": 43.6, "mmmu": 48.8},
      verified="2026-08"),

    # ------------------------------------------------------------------ Meta
    M("llama-4-maverick", "Llama 4 Maverick", "meta", rel="2025-04", arch="MoE", params="400B",
      active="17B", ctx=1048576, out=8192, inp=["text", "image"], outp=["text"],
      lic="Llama 4 Community", open=True, hosted_price=True, pin=0.22, pout=0.85,
      reason=False, tools=True, hf="meta-llama/Llama-4-Maverick-17B-128E-Instruct",
      desc="128 experts, 17B active — Meta's first natively multimodal open-weight model.",
      b={"mmlu_pro": 80.5, "gpqa": 69.8, "mmmu": 73.4, "arena": 1417},
      verified="2026-08"),
    M("llama-4-scout", "Llama 4 Scout", "meta", rel="2025-04", arch="MoE", params="109B",
      active="17B", ctx=10485760, out=8192, inp=["text", "image"], outp=["text"],
      lic="Llama 4 Community", open=True, hosted_price=True, pin=0.11, pout=0.34,
      reason=False, tools=True, hf="meta-llama/Llama-4-Scout-17B-16E-Instruct",
      desc="A ten-million-token context window — the longest ever shipped in open weights.",
      b={"mmlu_pro": 74.3, "gpqa": 57.2, "mmmu": 69.4},
      verified="2026-08"),
    M("llama-3-3-70b", "Llama 3.3 70B", "meta", rel="2024-12", params="70B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Llama 3.3 Community", open=True,
      hosted_price=True, pin=0.23, pout=0.40, reason=False, tools=True,
      hf="meta-llama/Llama-3.3-70B-Instruct",
      desc="405B-class quality distilled into 70B — for a year, the open-weight default.",
      b={"mmlu_pro": 68.9, "gpqa": 50.5, "humaneval": 88.4, "ifeval": 92.1, "arena": 1257},
      verified="2026-08"),
    M("llama-3-1-405b", "Llama 3.1 405B", "meta", rel="2024-07", params="405B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="Llama 3.1 Community", open=True,
      hosted_price=True, pin=3.50, pout=3.50, reason=False, tools=True,
      hf="meta-llama/Llama-3.1-405B-Instruct",
      desc="The release that first put a genuinely frontier-class model into open weights.",
      b={"mmlu_pro": 73.3, "gpqa": 51.1, "humaneval": 89.0, "ifeval": 88.6, "arena": 1266},
      verified="2026-08"),
    M("llama-3-1-8b", "Llama 3.1 8B", "meta", rel="2024-07", params="8B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Llama 3.1 Community", open=True,
      hosted_price=True, pin=0.03, pout=0.05, reason=False, tools=True,
      hf="meta-llama/Llama-3.1-8B-Instruct",
      desc="The most fine-tuned open model in existence, and the standard small baseline.",
      b={"mmlu_pro": 48.3, "gpqa": 32.8, "humaneval": 72.6, "ifeval": 80.4},
      verified="2026-08"),
    M("llama-3-2-90b", "Llama 3.2 90B Vision", "meta", rel="2024-09", params="90B", ctx=131072,
      out=8192, inp=["text", "image"], outp=["text"], lic="Llama 3.2 Community", open=True,
      hosted_price=True, pin=0.35, pout=0.40, reason=False, tools=True,
      hf="meta-llama/Llama-3.2-90B-Vision-Instruct",
      desc="Meta's first open vision-language model at scale.",
      b={"mmlu_pro": 68.0, "mmmu": 60.3},
      verified="2026-08"),
    M("llama-3-2-3b", "Llama 3.2 3B", "meta", rel="2024-09", params="3B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Llama 3.2 Community", open=True,
      hosted_price=True, pin=0.015, pout=0.025, reason=False, tools=True,
      hf="meta-llama/Llama-3.2-3B-Instruct",
      desc="Built for phones and edge devices, with tool calling intact.",
      b={"mmlu_pro": 33.0, "ifeval": 77.4},
      verified="2026-08"),

    # --------------------------------------------------------------- Mistral
    M("mistral-medium-3", "Mistral Medium 3", "mistral", rel="2025-05", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.40, pout=2.0, reason=False, tools=True,
      desc="Mistral's price-performance flagship, aimed squarely at enterprise deployment.",
      b={"mmlu_pro": 76.0, "gpqa": 62.4, "humaneval": 92.1, "mmmu": 66.1},
      verified="2026-08"),
    M("mistral-large-2", "Mistral Large 2", "mistral", rel="2024-11", params="123B", ctx=131072,
      out=8192, inp=["text", "image"], outp=["text"], lic="Mistral Research", open=True,
      hosted_price=True, pin=2.0, pout=6.0, reason=False, tools=True,
      hf="mistralai/Mistral-Large-Instruct-2411",
      desc="The 123B dense model that anchored Mistral's line for two years.",
      b={"mmlu_pro": 69.9, "gpqa": 48.0, "humaneval": 92.0, "arena": 1251},
      verified="2026-08"),
    M("magistral-medium", "Magistral Medium", "mistral", rel="2025-06", ctx=40960, out=40960,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=5.0, reason=True, tools=True,
      desc="Mistral's first reasoning model, with traces in the user's own language.",
      b={"aime": 73.6, "gpqa": 70.8},
      verified="2026-08"),
    M("magistral-small", "Magistral Small", "mistral", rel="2025-06", params="24B", ctx=40960,
      out=40960, inp=["text"], outp=["text"], lic="Apache 2.0", open=True,
      hosted_price=True, pin=0.50, pout=1.50, reason=True, tools=True,
      hf="mistralai/Magistral-Small-2506",
      desc="Open-weight reasoning at 24B — runs on a single 32GB card.",
      b={"aime": 70.7, "gpqa": 68.2},
      verified="2026-08"),
    M("mistral-small-3-2", "Mistral Small 3.2 24B", "mistral", rel="2025-06", params="24B",
      ctx=131072, out=8192, inp=["text", "image"], outp=["text"], lic="Apache 2.0", open=True,
      hosted_price=True, pin=0.10, pout=0.30, reason=False, tools=True,
      hf="mistralai/Mistral-Small-3.2-24B-Instruct-2506",
      desc="The best-regarded Apache-2.0 model in the 24B class, and multimodal.",
      b={"mmlu_pro": 69.1, "gpqa": 46.1, "humaneval": 92.9, "ifeval": 92.9},
      verified="2026-08"),
    M("devstral-medium", "Devstral Medium", "mistral", rel="2025-07", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.40, pout=2.0, reason=False, tools=True,
      desc="A coding agent model trained on repository-scale edit trajectories.",
      b={"swe": 61.6},
      verified="2026-08"),
    M("codestral-2508", "Codestral 25.08", "mistral", rel="2025-08", params="22B", ctx=262144,
      out=8192, inp=["text"], outp=["text"], lic="Mistral AI Non-Production", open=True,
      hosted_price=True, pin=0.30, pout=0.90, reason=False, tools=True,
      desc="Mistral's fill-in-the-middle code model, built for editor autocomplete.",
      b={"humaneval": 86.6},
      verified="2026-08"),
    M("ministral-8b", "Ministral 8B", "mistral", rel="2024-10", params="8B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Mistral Research", open=True,
      hosted_price=True, pin=0.10, pout=0.10, reason=False, tools=True,
      hf="mistralai/Ministral-8B-Instruct-2410",
      desc="An edge model with sliding-window attention for cheap long context.",
      b={"mmlu_pro": 47.0, "humaneval": 76.8},
      verified="2026-08"),
    M("mixtral-8x22b", "Mixtral 8x22B", "mistral", rel="2024-04", arch="MoE", params="141B",
      active="39B", ctx=65536, out=8192, inp=["text"], outp=["text"], lic="Apache 2.0",
      open=True, hosted_price=True, pin=0.90, pout=0.90, reason=False, tools=True,
      hf="mistralai/Mixtral-8x22B-Instruct-v0.1",
      desc="The sparse mixture of experts that popularised the architecture in open weights.",
      b={"mmlu_pro": 56.0, "humaneval": 75.0},
      verified="2026-08"),
    M("pixtral-large", "Pixtral Large", "mistral", rel="2024-11", params="124B", ctx=131072,
      out=8192, inp=["text", "image"], outp=["text"], lic="Mistral Research", open=True,
      hosted_price=True, pin=2.0, pout=6.0, reason=False, tools=True,
      hf="mistralai/Pixtral-Large-Instruct-2411",
      desc="A 124B multimodal model with a 1B vision encoder bolted to Mistral Large.",
      b={"mmmu": 64.0},
      verified="2026-08"),

    # -------------------------------------------------------------- DeepSeek
    M("deepseek-v3-2", "DeepSeek-V3.2", "deepseek", rel="2025-09", arch="MoE", params="685B",
      active="37B", ctx=163840, out=65536, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.28, pout=0.42, reason=True, tools=True,
      hf="deepseek-ai/DeepSeek-V3.2-Exp",
      desc="Introduced DeepSeek Sparse Attention, cutting long-context cost by roughly half "
           "at equal quality.",
      b={"gpqa": 79.9, "aime": 89.3, "lcb": 74.1, "mmlu_pro": 85.0},
      verified="2026-08"),
    M("deepseek-v3-1", "DeepSeek-V3.1", "deepseek", rel="2025-08", arch="MoE", params="685B",
      active="37B", ctx=131072, out=65536, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.28, pout=1.14, reason=True, tools=True,
      hf="deepseek-ai/DeepSeek-V3.1",
      desc="A single set of weights that switches between thinking and non-thinking modes.",
      b={"gpqa": 80.1, "aime": 88.4, "swe": 66.0, "mmlu_pro": 84.8},
      verified="2026-08"),
    M("deepseek-r1", "DeepSeek-R1", "deepseek", rel="2025-01", arch="MoE", params="671B",
      active="37B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.55, pout=2.19, reason=True, tools=True,
      hf="deepseek-ai/DeepSeek-R1",
      desc="The open-weight reasoning model that showed pure reinforcement learning could "
           "produce chain-of-thought without supervised traces.",
      b={"gpqa": 71.5, "aime": 79.8, "math": 97.3, "swe": 49.2, "mmlu_pro": 84.0, "arena": 1358},
      verified="2026-08"),
    M("deepseek-v3", "DeepSeek-V3", "deepseek", rel="2024-12", arch="MoE", params="671B",
      active="37B", ctx=131072, out=8192, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.27, pout=1.10, reason=False, tools=True,
      hf="deepseek-ai/DeepSeek-V3",
      desc="Trained for a reported $5.6M in GPU time — the release that reset assumptions "
           "about what frontier training has to cost.",
      b={"mmlu_pro": 75.9, "gpqa": 59.1, "humaneval": 82.6, "arena": 1318},
      verified="2026-08"),

    # ----------------------------------------------------------- Alibaba Qwen
    M("qwen3-max", "Qwen3-Max", "alibaba", rel="2025-09", arch="MoE", params="1T+",
      ctx=262144, out=32768, inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=1.20, pout=6.0, reason=True, tools=True,
      desc="Alibaba's largest model, and the first Qwen kept closed.",
      b={"gpqa": 85.4, "aime": 92.3, "swe": 69.6},
      verified="2026-08"),
    M("qwen3-235b-a22b", "Qwen3-235B-A22B", "alibaba", rel="2025-04", arch="MoE", params="235B",
      active="22B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="Apache 2.0",
      open=True, hosted_price=True, pin=0.20, pout=0.60, reason=True, tools=True,
      hf="Qwen/Qwen3-235B-A22B",
      desc="Apache-2.0 frontier weights with a hybrid thinking switch and 119 languages.",
      b={"gpqa": 71.1, "aime": 85.7, "lcb": 70.7, "mmlu_pro": 68.2, "arena": 1342},
      verified="2026-08"),
    M("qwen3-coder-480b", "Qwen3-Coder-480B-A35B", "alibaba", rel="2025-07", arch="MoE",
      params="480B", active="35B", ctx=262144, out=65536, inp=["text"], outp=["text"],
      lic="Apache 2.0", open=True, hosted_price=True, pin=0.30, pout=1.20,
      reason=False, tools=True, hf="Qwen/Qwen3-Coder-480B-A35B-Instruct",
      desc="The strongest open-weight agentic coding model of its generation, with a "
           "native 256k window extensible to a million.",
      b={"swe": 69.6, "lcb": 68.0},
      verified="2026-08"),
    M("qwen3-32b", "Qwen3-32B", "alibaba", rel="2025-04", params="32B", ctx=131072, out=32768,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.10, pout=0.30, reason=True, tools=True, hf="Qwen/Qwen3-32B",
      desc="A dense 32B with the same thinking switch as its much larger siblings.",
      b={"gpqa": 66.8, "aime": 81.4, "lcb": 65.7},
      verified="2026-08"),
    M("qwen3-30b-a3b", "Qwen3-30B-A3B", "alibaba", rel="2025-04", arch="MoE", params="30B",
      active="3B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="Apache 2.0",
      open=True, hosted_price=True, pin=0.08, pout=0.29, reason=True, tools=True,
      hf="Qwen/Qwen3-30B-A3B",
      desc="Only 3B parameters active per token — the fastest way to run a capable open "
           "model on modest hardware.",
      b={"gpqa": 65.8, "aime": 80.4, "lcb": 62.6},
      verified="2026-08"),
    M("qwq-32b", "QwQ-32B", "alibaba", rel="2025-03", params="32B", ctx=131072, out=32768,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.15, pout=0.20, reason=True, tools=True, hf="Qwen/QwQ-32B",
      desc="A 32B reasoning model that traded blows with 671B models on maths.",
      b={"gpqa": 65.2, "aime": 79.5, "lcb": 63.4},
      verified="2026-08"),
    M("qwen2-5-72b", "Qwen2.5-72B", "alibaba", rel="2024-09", params="72B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Qwen License", open=True, hosted_price=True,
      pin=0.35, pout=0.40, reason=False, tools=True, hf="Qwen/Qwen2.5-72B-Instruct",
      desc="The dense 72B that made Qwen a default choice outside China.",
      b={"mmlu_pro": 71.1, "gpqa": 49.0, "humaneval": 86.6, "arena": 1257},
      verified="2026-08"),
    M("qwen2-5-coder-32b", "Qwen2.5-Coder-32B", "alibaba", rel="2024-11", params="32B",
      ctx=131072, out=8192, inp=["text"], outp=["text"], lic="Apache 2.0", open=True,
      hosted_price=True, pin=0.07, pout=0.16, reason=False, tools=True,
      hf="Qwen/Qwen2.5-Coder-32B-Instruct",
      desc="For a long stretch the best open model you could run locally for code.",
      b={"humaneval": 92.7, "lcb": 31.4},
      verified="2026-08"),
    M("qwen2-5-vl-72b", "Qwen2.5-VL-72B", "alibaba", rel="2025-01", params="72B", ctx=131072,
      out=8192, inp=["text", "image", "video"], outp=["text"], lic="Qwen License", open=True,
      hosted_price=True, pin=0.40, pout=0.40, reason=False, tools=True,
      hf="Qwen/Qwen2.5-VL-72B-Instruct",
      desc="Open-weight vision at frontier quality, including document and GUI grounding.",
      b={"mmmu": 70.2},
      verified="2026-08"),

    # ------------------------------------------------------------------- xAI
    M("grok-4", "Grok 4", "xai", rel="2025-07", ctx=256000, out=64000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, pcache=0.75, reason=True, tools=True,
      desc="xAI's frontier reasoning model, with native search over X built into the loop.",
      b={"gpqa": 87.5, "aime": 94.0, "swe": 72.0},
      verified="2026-08"),
    M("grok-4-fast", "Grok 4 Fast", "xai", rel="2025-09", ctx=2000000, out=30000,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.20, pout=0.50, reason=True, tools=True,
      desc="A two-million-token window at a twentieth of Grok 4's price.",
      b={"gpqa": 85.7, "aime": 92.0},
      verified="2026-08"),
    M("grok-3", "Grok 3", "xai", rel="2025-02", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, reason=False, tools=True,
      desc="Trained on the Colossus cluster; the model that put xAI on the leaderboards.",
      b={"gpqa": 75.4, "aime": 83.9, "arena": 1402},
      verified="2026-08"),
    M("grok-3-mini", "Grok 3 Mini", "xai", rel="2025-02", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.30, pout=0.50, reason=True, tools=True,
      desc="A cheap reasoning model with visible thinking traces.",
      b={"gpqa": 66.2, "aime": 90.8},
      verified="2026-08"),
    M("grok-2", "Grok 2", "xai", rel="2024-08", params="270B", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Grok 2 Community", open=True,
      hosted_price=True, pin=2.0, pout=10.0, reason=False, tools=True, hf="xai-org/grok-2",
      desc="Released as open weights a year after launch.",
      b={"mmlu_pro": 75.5, "gpqa": 56.0, "humaneval": 88.4},
      verified="2026-08"),

    # ---------------------------------------------------------------- Amazon
    M("nova-premier", "Amazon Nova Premier", "amazon", rel="2025-04", ctx=1000000, out=32000,
      inp=["text", "image", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=2.50, pout=12.50, reason=False, tools=True,
      desc="The top of Amazon's own model line, built for distilling into smaller Novas.",
      b={"mmlu_pro": 80.0, "gpqa": 59.9, "mmmu": 69.6},
      verified="2026-08"),
    M("nova-pro", "Amazon Nova Pro", "amazon", rel="2024-12", ctx=300000, out=5120,
      inp=["text", "image", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=0.80, pout=3.20, reason=False, tools=True,
      desc="Amazon's balanced multimodal model, priced aggressively inside Bedrock.",
      b={"mmlu_pro": 75.5, "gpqa": 46.9, "humaneval": 89.0, "mmmu": 61.6},
      verified="2026-08"),
    M("nova-lite", "Amazon Nova Lite", "amazon", rel="2024-12", ctx=300000, out=5120,
      inp=["text", "image", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=0.06, pout=0.24, reason=False, tools=True,
      desc="Very cheap multimodal inference with a 300k window.",
      b={"mmlu_pro": 59.0, "mmmu": 56.2},
      verified="2026-08"),
    M("nova-micro", "Amazon Nova Micro", "amazon", rel="2024-12", ctx=128000, out=5120,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.035, pout=0.14, reason=False, tools=True,
      desc="Text-only and one of the cheapest models on any major cloud.",
      b={"mmlu_pro": 51.6, "humaneval": 81.1},
      verified="2026-08"),

    # ------------------------------------------------------------- Microsoft
    M("phi-4", "Phi-4", "microsoft", rel="2024-12", params="14B", ctx=16384, out=4096,
      inp=["text"], outp=["text"], lic="MIT", open=True, hosted_price=True,
      pin=0.07, pout=0.14, reason=False, tools=False, hf="microsoft/phi-4",
      desc="14B trained largely on synthetic curriculum data, and unusually strong at maths "
           "for its size.",
      b={"mmlu_pro": 70.4, "gpqa": 56.1, "humaneval": 82.6},
      verified="2026-08"),
    M("phi-4-reasoning-plus", "Phi-4-reasoning-plus", "microsoft", rel="2025-04", params="14B",
      ctx=32768, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.07, pout=0.35, reason=True, tools=False,
      hf="microsoft/Phi-4-reasoning-plus",
      desc="A 14B reasoning model distilled from o3-mini traces.",
      b={"aime": 78.0, "gpqa": 69.3},
      verified="2026-08"),
    M("phi-4-multimodal", "Phi-4-multimodal", "microsoft", rel="2025-02", params="5.6B",
      ctx=131072, out=4096, inp=["text", "image", "audio"], outp=["text"], lic="MIT",
      open=True, hosted_price=True, pin=0.05, pout=0.10, reason=False, tools=False,
      hf="microsoft/Phi-4-multimodal-instruct",
      desc="Text, vision and speech in 5.6B parameters, MIT-licensed.",
      b={"mmmu": 55.1},
      verified="2026-08"),

    # ---------------------------------------------------------------- Cohere
    M("command-a", "Command A", "cohere", rel="2025-03", params="111B", ctx=256000, out=8192,
      inp=["text"], outp=["text"], lic="CC-BY-NC", open=True, hosted_price=True,
      pin=2.50, pout=10.0, reason=False, tools=True, hf="CohereLabs/c4ai-command-a-03-2025",
      desc="Runs on two GPUs, tuned for retrieval-augmented generation and 23 languages.",
      b={"mmlu_pro": 68.0, "ifeval": 90.9, "arena": 1305},
      verified="2026-08"),
    M("command-r-plus", "Command R+", "cohere", rel="2024-08", params="104B", ctx=128000,
      out=4096, inp=["text"], outp=["text"], lic="CC-BY-NC", open=True, hosted_price=True,
      pin=2.50, pout=10.0, reason=False, tools=True, hf="CohereForAI/c4ai-command-r-plus-08-2024",
      desc="The model that made citation-grounded RAG a first-class API feature.",
      b={"mmlu_pro": 56.0, "humaneval": 71.0, "arena": 1215},
      verified="2026-08"),
    M("command-r7b", "Command R7B", "cohere", rel="2024-12", params="7B", ctx=128000, out=4096,
      inp=["text"], outp=["text"], lic="CC-BY-NC", open=True, hosted_price=True,
      pin=0.0375, pout=0.15, reason=False, tools=True, hf="CohereForAI/c4ai-command-r7b-12-2024",
      desc="Cohere's smallest — built for on-device RAG and tool use.",
      b={"mmlu_pro": 42.0, "ifeval": 77.9},
      verified="2026-08"),

    # ------------------------------------------------------------------ AI21
    M("jamba-1-6-large", "Jamba 1.6 Large", "ai21", rel="2025-03", arch="Hybrid SSM-Transformer",
      params="398B", active="94B", ctx=256000, out=4096, inp=["text"], outp=["text"],
      lic="Jamba Open Model", open=True, hosted_price=True, pin=2.0, pout=8.0,
      reason=False, tools=True, hf="ai21labs/AI21-Jamba-Large-1.6",
      desc="A Mamba-Transformer hybrid — state-space layers keep long-context memory flat "
           "instead of quadratic.",
      b={"mmlu_pro": 60.0, "ifeval": 88.0},
      verified="2026-08"),
    M("jamba-1-6-mini", "Jamba 1.6 Mini", "ai21", rel="2025-03", arch="Hybrid SSM-Transformer",
      params="52B", active="12B", ctx=256000, out=4096, inp=["text"], outp=["text"],
      lic="Jamba Open Model", open=True, hosted_price=True, pin=0.20, pout=0.40,
      reason=False, tools=True, hf="ai21labs/AI21-Jamba-Mini-1.6",
      desc="256k context on a single 80GB card, thanks to the hybrid architecture.",
      b={"mmlu_pro": 43.0},
      verified="2026-08"),

    # -------------------------------------------------------------- Moonshot
    M("kimi-k2-thinking", "Kimi K2 Thinking", "moonshot", rel="2025-11", arch="MoE",
      params="1T", active="32B", ctx=262144, out=131072, inp=["text"], outp=["text"],
      lic="Modified MIT", open=True, hosted_price=True, pin=0.60, pout=2.50,
      reason=True, tools=True, hf="moonshotai/Kimi-K2-Thinking",
      desc="A trillion-parameter open-weight reasoning model that holds tool-use chains "
           "across hundreds of sequential calls.",
      b={"gpqa": 84.5, "aime": 94.5, "swe": 71.3, "lcb": 83.1},
      verified="2026-08"),
    M("kimi-k2", "Kimi K2 Instruct", "moonshot", rel="2025-07", arch="MoE", params="1T",
      active="32B", ctx=131072, out=16384, inp=["text"], outp=["text"],
      lic="Modified MIT", open=True, hosted_price=True, pin=0.60, pout=2.50,
      reason=False, tools=True, hf="moonshotai/Kimi-K2-Instruct",
      desc="The first open-weight trillion-parameter model, trained with the Muon optimiser.",
      b={"swe": 65.8, "lcb": 53.7, "mmlu_pro": 81.1, "arena": 1420},
      verified="2026-08"),

    # ------------------------------------------------------------------ Z.ai
    M("glm-4-6", "GLM-4.6", "zai", rel="2025-09", arch="MoE", params="357B", active="32B",
      ctx=204800, out=131072, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.60, pout=2.20, reason=True, tools=True, hf="zai-org/GLM-4.6",
      desc="Widely used as an open drop-in for coding agents, with a 200k window.",
      b={"gpqa": 82.9, "aime": 93.9, "swe": 68.0, "lcb": 82.8},
      verified="2026-08"),
    M("glm-4-5", "GLM-4.5", "zai", rel="2025-07", arch="MoE", params="355B", active="32B",
      ctx=131072, out=98304, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.60, pout=2.20, reason=True, tools=True, hf="zai-org/GLM-4.5",
      desc="Unified reasoning, coding and agentic behaviour in one open MIT release.",
      b={"gpqa": 79.1, "aime": 91.0, "swe": 64.2},
      verified="2026-08"),
    M("glm-4-5-air", "GLM-4.5-Air", "zai", rel="2025-07", arch="MoE", params="106B",
      active="12B", ctx=131072, out=98304, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.20, pout=1.10, reason=True, tools=True, hf="zai-org/GLM-4.5-Air",
      desc="A third the size of GLM-4.5 and close behind it — fits comfortably on one node.",
      b={"gpqa": 75.0, "aime": 89.4, "swe": 57.6},
      verified="2026-08"),

    # --------------------------------------------------------------- MiniMax
    M("minimax-m2", "MiniMax-M2", "minimax", rel="2025-10", arch="MoE", params="230B",
      active="10B", ctx=204800, out=131072, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.30, pout=1.20, reason=True, tools=True, hf="MiniMaxAI/MiniMax-M2",
      desc="Only 10B active parameters, which makes it unusually fast for its class on "
           "agentic workloads.",
      b={"gpqa": 78.0, "aime": 78.0, "swe": 69.4},
      verified="2026-08"),
    M("minimax-m1", "MiniMax-M1", "minimax", rel="2025-06", arch="MoE", params="456B",
      active="46B", ctx=1000000, out=80000, inp=["text"], outp=["text"], lic="Apache 2.0",
      open=True, hosted_price=True, pin=0.40, pout=2.10, reason=True, tools=True,
      hf="MiniMaxAI/MiniMax-M1-80k",
      desc="A million-token open-weight reasoning model using lightning attention.",
      b={"aime": 86.0, "swe": 56.0},
      verified="2026-08"),

    # ---------------------------------------------------------------- NVIDIA
    M("nemotron-ultra-253b", "Llama-3.1-Nemotron-Ultra-253B", "nvidia", rel="2025-04",
      params="253B", ctx=131072, out=32768, inp=["text"], outp=["text"],
      lic="NVIDIA Open Model", open=True, hosted_price=True, pin=0.60, pout=1.80,
      reason=True, tools=True, hf="nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
      desc="Llama 3.1 405B pruned to 253B by neural architecture search, then re-trained "
           "for reasoning.",
      b={"gpqa": 76.0, "aime": 80.1, "ifeval": 89.5},
      verified="2026-08"),
    M("nemotron-super-49b", "Llama-3.3-Nemotron-Super-49B", "nvidia", rel="2025-03",
      params="49B", ctx=131072, out=32768, inp=["text"], outp=["text"],
      lic="NVIDIA Open Model", open=True, hosted_price=True, pin=0.13, pout=0.40,
      reason=True, tools=True, hf="nvidia/Llama-3_3-Nemotron-Super-49B-v1",
      desc="Distilled to fit a single H100 while keeping a reasoning toggle.",
      b={"gpqa": 66.7, "aime": 67.5},
      verified="2026-08"),

    # -------------------------------------------------------------- Allen AI
    M("olmo-2-32b", "OLMo 2 32B", "allenai", rel="2025-03", params="32B", ctx=4096, out=4096,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.20, pout=0.40, reason=False, tools=False, hf="allenai/OLMo-2-0325-32B-Instruct",
      desc="Fully open: weights, data, code and training logs all published. The most "
           "reproducible model on this list.",
      b={"mmlu_pro": 47.0, "humaneval": 68.0},
      verified="2026-08"),
    M("molmo-72b", "Molmo 72B", "allenai", rel="2024-09", params="72B", ctx=4096, out=4096,
      inp=["text", "image"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.35, pout=0.40, reason=False, tools=False, hf="allenai/Molmo-72B-0924",
      desc="Trained without any distillation from closed models, and able to point at "
           "image regions.",
      b={"mmmu": 54.1},
      verified="2026-08"),

    # ----------------------------------------------------------------- 01.AI
    M("yi-large", "Yi-Large", "01ai", rel="2024-05", ctx=32768, out=4096,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=3.0, reason=False, tools=True,
      desc="01.AI's bilingual flagship, and an early top-ten finish on LMArena for China.",
      b={"mmlu_pro": 60.0, "humaneval": 80.0, "arena": 1213},
      verified="2026-08"),
    M("yi-1-5-34b", "Yi-1.5-34B", "01ai", rel="2024-05", params="34B", ctx=32768, out=4096,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.15, pout=0.15, reason=False, tools=False, hf="01-ai/Yi-1.5-34B-Chat",
      desc="A well-liked Apache-2.0 34B for bilingual work.",
      b={"mmlu_pro": 48.0, "humaneval": 75.2},
      verified="2026-08"),

    # ------------------------------------------------------------------ Reka
    M("reka-flash-3", "Reka Flash 3", "reka", rel="2025-03", params="21B", ctx=32768, out=8192,
      inp=["text", "image"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.10, pout=0.30, reason=True, tools=True, hf="RekaAI/reka-flash-3",
      desc="A 21B reasoning model with an explicit budget-forcing token to cap thinking length.",
      b={"gpqa": 51.2, "aime": 65.0},
      verified="2026-08"),
    M("reka-core", "Reka Core", "reka", rel="2024-04", ctx=128000, out=4096,
      inp=["text", "image", "video", "audio"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=2.0, reason=False, tools=True,
      desc="One of the few models that ingests video and audio natively alongside text.",
      b={"mmlu_pro": 55.0, "mmmu": 56.3},
      verified="2026-08"),

    # ------------------------------------------------------------- Liquid AI
    M("lfm2-8b-a1b", "LFM2-8B-A1B", "liquid", rel="2025-10", arch="MoE", params="8.3B",
      active="1.5B", ctx=32768, out=8192, inp=["text"], outp=["text"], lic="LFM Open", open=True,
      hosted_price=True, pin=0.02, pout=0.05, reason=False, tools=True, hf="LiquidAI/LFM2-8B-A1B",
      desc="A convolution-and-attention hybrid rather than a plain transformer, aimed at "
           "phones and embedded hardware.",
      b={"mmlu_pro": 40.0},
      verified="2026-08"),

    # ------------------------------------------------------------ Perplexity
    M("sonar-reasoning-pro", "Sonar Reasoning Pro", "perplexity", rel="2025-03", ctx=127072,
      out=8192, inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=2.0, pout=8.0, reason=True, tools=True, search=True,
      desc="A reasoning model wired directly to Perplexity's live web index, with citations "
           "in every answer.",
      b={"gpqa": 68.0},
      verified="2026-08"),
    M("sonar-pro", "Sonar Pro", "perplexity", rel="2025-01", ctx=200000, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=3.0, pout=15.0, reason=False, tools=True, search=True,
      desc="Search-grounded answers as an API primitive rather than a tool you assemble.",
      b={},
      verified="2026-08"),
    M("r1-1776", "R1-1776", "perplexity", rel="2025-02", arch="MoE", params="671B",
      active="37B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=2.0, pout=8.0, reason=True, tools=False, hf="perplexity-ai/r1-1776",
      desc="DeepSeek-R1 post-trained to remove refusal patterns on politically sensitive "
           "topics, released openly.",
      b={"aime": 78.0},
      verified="2026-08"),

    # ----------------------------------------------------------------- Baidu
    M("ernie-4-5-300b", "ERNIE 4.5 300B-A47B", "baidu", rel="2025-06", arch="MoE",
      params="300B", active="47B", ctx=131072, out=8192, inp=["text", "image"], outp=["text"],
      lic="Apache 2.0", open=True, hosted_price=True, pin=0.28, pout=1.10,
      reason=False, tools=True, hf="baidu/ERNIE-4.5-300B-A47B-PT",
      desc="Baidu's first open-weight release, with separate text and vision expert routing.",
      b={"mmlu_pro": 74.0},
      verified="2026-08"),
    M("ernie-x1", "ERNIE X1", "baidu", rel="2025-03", ctx=131072, out=8192,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=0.28, pout=1.10, reason=True, tools=True,
      desc="Baidu's reasoning model, positioned against R1 at roughly half the price.",
      b={},
      verified="2026-08"),

    # --------------------------------------------------------------- Tencent
    M("hunyuan-a13b", "Hunyuan-A13B", "tencent", rel="2025-06", arch="MoE", params="80B",
      active="13B", ctx=262144, out=32768, inp=["text"], outp=["text"],
      lic="Tencent Hunyuan Community", open=True, hosted_price=True, pin=0.30, pout=1.00,
      reason=True, tools=True, hf="tencent/Hunyuan-A13B-Instruct",
      desc="Fast and slow thinking modes in one model, at 13B active parameters.",
      b={"gpqa": 71.2, "aime": 87.3},
      verified="2026-08"),

    # ------------------------------------------------------------- ByteDance
    M("seed-oss-36b", "Seed-OSS-36B", "bytedance", rel="2025-08", params="36B", ctx=524288,
      out=32768, inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.15, pout=0.60, reason=True, tools=True, hf="ByteDance-Seed/Seed-OSS-36B-Instruct",
      desc="A 512k-context open model with a thinking budget you set in tokens per request.",
      b={"gpqa": 71.4, "aime": 91.7},
      verified="2026-08"),

    # --------------------------------------------------------------- StepFun
    M("step-3", "Step-3", "stepfun", rel="2025-07", arch="MoE", params="321B", active="38B",
      ctx=65536, out=16384, inp=["text", "image"], outp=["text"], lic="Apache 2.0", open=True,
      hosted_price=True, pin=0.30, pout=1.20, reason=False, tools=True, hf="stepfun-ai/step3",
      desc="A multimodal MoE designed around decoding cost rather than parameter count.",
      b={"mmmu": 74.2},
      verified="2026-08"),

    # ------------------------------------------------------------------- IBM
    M("granite-3-3-8b", "Granite 3.3 8B", "ibm", rel="2025-04", params="8B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.03, pout=0.06, reason=True, tools=True, hf="ibm-granite/granite-3.3-8b-instruct",
      desc="Enterprise-focused, with published training-data provenance and an IP indemnity.",
      b={"mmlu_pro": 45.0, "ifeval": 85.9},
      verified="2026-08"),

    # ------------------------------------------------------------ Databricks
    M("dbrx", "DBRX Instruct", "databricks", rel="2024-03", arch="MoE", params="132B",
      active="36B", ctx=32768, out=4096, inp=["text"], outp=["text"],
      lic="Databricks Open Model", open=True, hosted_price=True, pin=0.75, pout=2.25,
      reason=False, tools=False, hf="databricks/dbrx-instruct",
      desc="A fine-grained MoE with 16 experts, four active — an influential 2024 open release.",
      b={"mmlu_pro": 45.0, "humaneval": 70.1},
      verified="2026-08"),

    # ---------------------------------------------------------------- Upstage
    M("solar-pro-2", "Solar Pro 2", "upstage", rel="2025-05", params="31B", ctx=65536, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.50, pout=0.50, reason=True, tools=True,
      desc="A Korean-first model that stays competitive in English at 31B.",
      b={"mmlu_pro": 66.0},
      verified="2026-08"),

    # ---------------------------------------------------------- Nous Research
    M("hermes-4-405b", "Hermes 4 405B", "nous", rel="2025-08", params="405B", ctx=131072,
      out=32768, inp=["text"], outp=["text"], lic="Llama 3.1 Community", open=True,
      hosted_price=True, pin=1.0, pout=3.0, reason=True, tools=True,
      hf="NousResearch/Hermes-4-405B",
      desc="A steerable, minimally-filtered fine-tune of Llama 3.1 405B with hybrid reasoning.",
      b={"aime": 78.1, "gpqa": 70.5},
      verified="2026-08"),

    # -------------------------------------------------------- Inception Labs
    M("mercury-coder", "Mercury Coder", "inception", rel="2025-02", ctx=32768, out=16384,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.25, pout=1.0, reason=False, tools=True, diffusion=True,
      desc="A diffusion language model rather than an autoregressive one — it denoises whole "
           "blocks of tokens at once, which is why it is so fast.",
      b={"humaneval": 90.0},
      verified="2026-08"),

    # ------------------------------------- Newest frontier, specs unpublished
    #
    # These ship as API model IDs before a full model card exists. Everything
    # not yet published is left empty rather than guessed, and the pages mark
    # them provisional.
    M("claude-opus-5", "Claude Opus 5", "anthropic", rel="2026", lic="Proprietary", open=False,
      api_id="claude-opus-5", reason=True, tools=True, inp=["text", "image"], outp=["text"],
      provisional=True,
      desc="The current head of the Claude line. Available by API ID; a full specification "
           "and benchmark card had not been published when this catalogue was last checked.",
      b={}, verified="2026-09"),
    M("claude-sonnet-5", "Claude Sonnet 5", "anthropic", rel="2026", lic="Proprietary", open=False,
      api_id="claude-sonnet-5", reason=True, tools=True, inp=["text", "image"], outp=["text"],
      provisional=True,
      desc="The mid-tier Claude 5. Available by API ID; specifications not yet published.",
      b={}, verified="2026-09"),
    M("claude-fable-5-1", "Claude Fable 5.1", "anthropic", rel="2026", lic="Proprietary",
      open=False, api_id="claude-fable-5-1", reason=True, tools=True,
      inp=["text", "image"], outp=["text"], provisional=True,
      desc="A Claude 5 variant available by API ID. Specifications not yet published.",
      b={}, verified="2026-09"),

    # ----------------------------------------------- Earlier OpenAI / Google
    M("gpt-4-turbo", "GPT-4 Turbo", "openai", rel="2024-04", ctx=128000, out=4096,
      inp=["text", "image"], outp=["text"], lic="Proprietary", open=False,
      pin=10.0, pout=30.0, reason=False, tools=True, cut="2023-12",
      desc="The 2024 workhorse that first brought GPT-4 quality to a 128k window.",
      b={"mmlu_pro": 63.7, "gpqa": 48.0, "humaneval": 87.1, "mmmu": 63.1, "arena": 1256},
      verified="2026-08"),
    M("gpt-3-5-turbo", "GPT-3.5 Turbo", "openai", rel="2023-11", ctx=16385, out=4096,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.50, pout=1.50, reason=False, tools=True, cut="2021-09",
      desc="The model that started the commodity-LLM era. Kept here as a baseline.",
      b={"mmlu_pro": 38.0, "humaneval": 68.0, "arena": 1106},
      verified="2026-08"),
    M("o1-mini", "o1-mini", "openai", rel="2024-09", ctx=128000, out=65536,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=1.10, pout=4.40, reason=True, tools=False, cut="2023-10",
      desc="The first small reasoning model, focused on maths and code.",
      b={"aime": 63.6, "gpqa": 60.0, "humaneval": 92.4},
      verified="2026-08"),
    M("gemini-2-0-flash-lite", "Gemini 2.0 Flash-Lite", "google", rel="2025-02", ctx=1048576,
      out=8192, inp=["text", "image", "audio", "video"], outp=["text"],
      lic="Proprietary", open=False, pin=0.075, pout=0.30, reason=False, tools=True,
      cut="2024-08",
      desc="Google's cheapest tier of the 2.0 generation.",
      b={"mmlu_pro": 71.6, "gpqa": 51.5},
      verified="2026-08"),
    M("gemini-1-5-flash", "Gemini 1.5 Flash", "google", rel="2024-05", ctx=1048576, out=8192,
      inp=["text", "image", "audio", "video"], outp=["text"], lic="Proprietary", open=False,
      pin=0.075, pout=0.30, reason=False, tools=True, cut="2023-11",
      desc="Distilled from 1.5 Pro; the first genuinely cheap million-token model.",
      b={"mmlu_pro": 67.3, "gpqa": 51.0, "mmmu": 56.1},
      verified="2026-08"),
    M("gemma-2-27b", "Gemma 2 27B", "google", rel="2024-06", params="27B", ctx=8192, out=8192,
      inp=["text"], outp=["text"], lic="Gemma Terms of Use", open=True, hosted_price=True,
      pin=0.27, pout=0.27, reason=False, tools=False, hf="google/gemma-2-27b-it",
      desc="Punched well above its size in 2024 and stayed a common local default.",
      b={"mmlu_pro": 56.0, "humaneval": 51.8, "arena": 1220},
      verified="2026-08"),
    M("gemma-2-9b", "Gemma 2 9B", "google", rel="2024-06", params="9B", ctx=8192, out=8192,
      inp=["text"], outp=["text"], lic="Gemma Terms of Use", open=True, hosted_price=True,
      pin=0.06, pout=0.06, reason=False, tools=False, hf="google/gemma-2-9b-it",
      desc="Trained by distillation from a larger teacher rather than from scratch.",
      b={"mmlu_pro": 45.0, "humaneval": 40.2, "arena": 1192},
      verified="2026-08"),

    # ------------------------------------------------ More Llama / Qwen tiers
    M("llama-3-1-70b", "Llama 3.1 70B", "meta", rel="2024-07", params="70B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="Llama 3.1 Community", open=True,
      hosted_price=True, pin=0.12, pout=0.30, reason=False, tools=True,
      hf="meta-llama/Llama-3.1-70B-Instruct",
      desc="The mid-tier of the 3.1 family, superseded by 3.3 70B at the same size.",
      b={"mmlu_pro": 66.4, "gpqa": 46.7, "humaneval": 80.5, "ifeval": 87.5},
      verified="2026-08"),
    M("llama-3-2-11b", "Llama 3.2 11B Vision", "meta", rel="2024-09", params="11B", ctx=131072,
      out=8192, inp=["text", "image"], outp=["text"], lic="Llama 3.2 Community", open=True,
      hosted_price=True, pin=0.055, pout=0.055, reason=False, tools=True,
      hf="meta-llama/Llama-3.2-11B-Vision-Instruct",
      desc="The small end of Meta's open vision line.",
      b={"mmlu_pro": 47.0, "mmmu": 50.7},
      verified="2026-08"),
    M("llama-3-2-1b", "Llama 3.2 1B", "meta", rel="2024-09", params="1B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Llama 3.2 Community", open=True, hosted_price=True,
      pin=0.01, pout=0.02, reason=False, tools=False, hf="meta-llama/Llama-3.2-1B-Instruct",
      desc="Small enough to run on a phone CPU.",
      b={"mmlu_pro": 22.0, "ifeval": 59.5},
      verified="2026-08"),
    M("qwen3-14b", "Qwen3-14B", "alibaba", rel="2025-04", params="14B", ctx=131072, out=32768,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.06, pout=0.24, reason=True, tools=True, hf="Qwen/Qwen3-14B",
      desc="The largest Qwen3 that fits comfortably in 24GB with room for context.",
      b={"gpqa": 64.0, "aime": 79.3, "lcb": 63.5},
      verified="2026-08"),
    M("qwen3-8b", "Qwen3-8B", "alibaba", rel="2025-04", params="8B", ctx=131072, out=32768,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.035, pout=0.138, reason=True, tools=True, hf="Qwen/Qwen3-8B",
      desc="Reasoning in 8B — the smallest size where the thinking switch still pays off.",
      b={"gpqa": 62.0, "aime": 76.0},
      verified="2026-08"),
    M("qwen3-4b", "Qwen3-4B", "alibaba", rel="2025-04", params="4B", ctx=131072, out=32768,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.02, pout=0.06, reason=True, tools=True, hf="Qwen/Qwen3-4B",
      desc="Laptop-scale reasoning with a 128k window.",
      b={"gpqa": 55.9, "aime": 73.8},
      verified="2026-08"),
    M("qwen2-5-32b", "Qwen2.5-32B", "alibaba", rel="2024-09", params="32B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.08, pout=0.20, reason=False, tools=True, hf="Qwen/Qwen2.5-32B-Instruct",
      desc="The Apache-2.0 32B that anchored a generation of local deployments.",
      b={"mmlu_pro": 69.0, "humaneval": 88.4},
      verified="2026-08"),
    M("qwen2-5-7b", "Qwen2.5-7B", "alibaba", rel="2024-09", params="7B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.025, pout=0.05, reason=False, tools=True, hf="Qwen/Qwen2.5-7B-Instruct",
      desc="One of the most widely fine-tuned small models in the open ecosystem.",
      b={"mmlu_pro": 56.3, "humaneval": 84.8},
      verified="2026-08"),

    # ------------------------------------------- More DeepSeek / distillations
    M("deepseek-r1-distill-32b", "DeepSeek-R1-Distill-Qwen-32B", "deepseek", rel="2025-01",
      params="32B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.12, pout=0.18, reason=True, tools=False,
      hf="deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
      desc="R1's reasoning traces distilled into Qwen2.5-32B — the cheapest way to get "
           "R1-class maths locally.",
      b={"aime": 72.6, "gpqa": 62.1, "math": 94.3},
      verified="2026-08"),
    M("deepseek-r1-distill-8b", "DeepSeek-R1-Distill-Llama-8B", "deepseek", rel="2025-01",
      params="8B", ctx=131072, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.04, pout=0.04, reason=True, tools=False,
      hf="deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
      desc="Reasoning distilled all the way down to 8B.",
      b={"aime": 50.4, "math": 89.1},
      verified="2026-08"),
    M("deepseek-coder-v2", "DeepSeek-Coder-V2", "deepseek", rel="2024-06", arch="MoE",
      params="236B", active="21B", ctx=131072, out=8192, inp=["text"], outp=["text"],
      lic="DeepSeek License", open=True, hosted_price=True, pin=0.14, pout=0.28,
      reason=False, tools=True, hf="deepseek-ai/DeepSeek-Coder-V2-Instruct",
      desc="The first open code model to match GPT-4 Turbo on HumanEval.",
      b={"humaneval": 90.2, "mmlu_pro": 60.0},
      verified="2026-08"),

    # ----------------------------------------------------- More Mistral / xAI
    M("mistral-nemo", "Mistral NeMo 12B", "mistral", rel="2024-07", params="12B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.03, pout=0.07, reason=False, tools=True, hf="mistralai/Mistral-Nemo-Instruct-2407",
      desc="Built with NVIDIA; the Tekken tokenizer made it notably efficient on non-English text.",
      b={"mmlu_pro": 50.0, "humaneval": 77.4},
      verified="2026-08"),
    M("mistral-7b", "Mistral 7B", "mistral", rel="2023-09", params="7B", ctx=32768, out=8192,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.025, pout=0.025, reason=False, tools=False,
      hf="mistralai/Mistral-7B-Instruct-v0.3",
      desc="The release that proved a small Apache-2.0 model could beat a much larger one, "
           "and set off the open fine-tuning boom.",
      b={"mmlu_pro": 30.0, "humaneval": 40.2},
      verified="2026-08"),
    M("grok-code-fast-1", "Grok Code Fast 1", "xai", rel="2025-08", ctx=256000, out=10000,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.20, pout=1.50, reason=True, tools=True,
      desc="Priced and tuned specifically for high-frequency agentic coding loops.",
      b={"swe": 70.8},
      verified="2026-08"),

    # ---------------------------------------------------- Remaining catalogue
    M("glm-4-9b", "GLM-4-9B", "zai", rel="2024-06", params="9B", ctx=131072, out=8192,
      inp=["text"], outp=["text"], lic="GLM License", open=True, hosted_price=True,
      pin=0.03, pout=0.06, reason=False, tools=True, hf="THUDM/glm-4-9b-chat",
      desc="A strong bilingual 9B with long context, widely used in Chinese deployments.",
      b={"mmlu_pro": 45.0, "humaneval": 71.8},
      verified="2026-08"),
    M("kimi-dev-72b", "Kimi-Dev-72B", "moonshot", rel="2025-06", params="72B", ctx=131072,
      out=16384, inp=["text"], outp=["text"], lic="Modified MIT", open=True,
      hosted_price=True, pin=0.29, pout=1.15, reason=False, tools=True,
      hf="moonshotai/Kimi-Dev-72B",
      desc="A 72B tuned purely for issue resolution — briefly the best open SWE-bench score.",
      b={"swe": 60.4},
      verified="2026-08"),
    M("hunyuan-large", "Hunyuan-Large", "tencent", rel="2024-11", arch="MoE", params="389B",
      active="52B", ctx=262144, out=8192, inp=["text"], outp=["text"],
      lic="Tencent Hunyuan Community", open=True, hosted_price=True, pin=0.50, pout=1.50,
      reason=False, tools=True, hf="tencent/Tencent-Hunyuan-Large",
      desc="At release, the largest open transformer MoE published by anyone.",
      b={"mmlu_pro": 60.2, "humaneval": 71.4},
      verified="2026-08"),
    M("nemotron-nano-9b", "Nemotron Nano 9B v2", "nvidia", rel="2025-08", arch="Hybrid Mamba",
      params="9B", ctx=131072, out=32768, inp=["text"], outp=["text"],
      lic="NVIDIA Open Model", open=True, hosted_price=True, pin=0.04, pout=0.16,
      reason=True, tools=True, hf="nvidia/NVIDIA-Nemotron-Nano-9B-v2",
      desc="A Mamba-Transformer hybrid with a reasoning budget you can cap per request.",
      b={"aime": 72.1, "gpqa": 64.0},
      verified="2026-08"),
    M("olmo-2-13b", "OLMo 2 13B", "allenai", rel="2024-11", params="13B", ctx=4096, out=4096,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.10, pout=0.20, reason=False, tools=False, hf="allenai/OLMo-2-1124-13B-Instruct",
      desc="Fully open training data and code, at a size anyone can reproduce.",
      b={"mmlu_pro": 35.0, "humaneval": 56.0},
      verified="2026-08"),
    M("phi-3-5-moe", "Phi-3.5-MoE", "microsoft", rel="2024-08", arch="MoE", params="42B",
      active="6.6B", ctx=131072, out=4096, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.08, pout=0.16, reason=False, tools=False,
      hf="microsoft/Phi-3.5-MoE-instruct",
      desc="16 experts, two active — MIT-licensed and multilingual.",
      b={"mmlu_pro": 54.0, "humaneval": 70.7},
      verified="2026-08"),
    M("falcon-3-10b", "Falcon 3 10B", "tii", rel="2024-12", params="10B", ctx=32768, out=8192,
      inp=["text"], outp=["text"], lic="Falcon LLM License", open=True, hosted_price=True,
      pin=0.05, pout=0.10, reason=False, tools=False, hf="tiiuae/Falcon3-10B-Instruct",
      desc="Grown from a 7B by depth up-scaling rather than trained from scratch.",
      b={"mmlu_pro": 44.0, "humaneval": 73.8},
      verified="2026-08"),
    M("falcon-h1-34b", "Falcon-H1 34B", "tii", rel="2025-05", arch="Hybrid Mamba", params="34B",
      ctx=262144, out=16384, inp=["text"], outp=["text"], lic="Falcon LLM License", open=True,
      hosted_price=True, pin=0.15, pout=0.45, reason=False, tools=True,
      hf="tiiuae/Falcon-H1-34B-Instruct",
      desc="Runs attention and state-space layers in parallel rather than in sequence.",
      b={"mmlu_pro": 58.0},
      verified="2026-08"),
    M("falcon-180b", "Falcon 180B", "tii", rel="2023-09", params="180B", ctx=2048, out=2048,
      inp=["text"], outp=["text"], lic="Falcon 180B TII License", open=True,
      hosted_price=True, pin=1.80, pout=1.80, reason=False, tools=False,
      hf="tiiuae/falcon-180B-chat",
      desc="The largest open model of 2023, and a marker of how fast the frontier moved.",
      b={"mmlu_pro": 30.0},
      verified="2026-08"),
    M("xlam-2-70b", "xLAM-2-70B", "salesforce", rel="2025-03", params="70B", ctx=131072,
      out=8192, inp=["text"], outp=["text"], lic="CC-BY-NC", open=True, hosted_price=True,
      pin=0.30, pout=0.60, reason=False, tools=True,
      hf="Salesforce/Llama-xLAM-2-70b-fc-r",
      desc="Trained specifically for multi-turn function calling rather than chat.",
      b={"ifeval": 88.0},
      verified="2026-08"),
    M("arctic", "Snowflake Arctic", "snowflake", rel="2024-04", arch="MoE", params="480B",
      active="17B", ctx=4096, out=4096, inp=["text"], outp=["text"], lic="Apache 2.0",
      open=True, hosted_price=True, pin=0.60, pout=1.80, reason=False, tools=False,
      hf="Snowflake/snowflake-arctic-instruct",
      desc="128 fine-grained experts, built for SQL and enterprise analytics rather than chat.",
      b={"mmlu_pro": 40.0, "humaneval": 64.3},
      verified="2026-08"),
    M("palmyra-x5", "Palmyra X5", "writer", rel="2025-04", ctx=1000000, out=8192,
      inp=["text"], outp=["text"], lic="Proprietary", open=False,
      pin=0.60, pout=6.0, reason=True, tools=True,
      desc="A million-token enterprise model tuned for long-document workflows.",
      b={"ifeval": 87.0},
      verified="2026-08"),
    M("exaone-4-32b", "EXAONE 4.0 32B", "lgai", rel="2025-07", params="32B", ctx=131072,
      out=32768, inp=["text"], outp=["text"], lic="EXAONE AI Model License", open=True,
      hosted_price=True, pin=0.15, pout=0.45, reason=True, tools=True,
      hf="LGAI-EXAONE/EXAONE-4.0-32B",
      desc="Korean-English bilingual with a unified reasoning and non-reasoning mode.",
      b={"gpqa": 66.7, "aime": 85.3},
      verified="2026-08"),
    M("hyperclova-x-seed-14b", "HyperCLOVA X SEED 14B", "naver", rel="2025-06", params="14B",
      ctx=32768, out=8192, inp=["text"], outp=["text"], lic="HyperCLOVA X SEED License",
      open=True, hosted_price=True, pin=0.08, pout=0.16, reason=False, tools=True,
      hf="naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
      desc="Naver's open Korean-first release, trained largely on domestic data.",
      b={},
      verified="2026-08"),
    M("sarvam-m", "Sarvam-M", "sarvam", rel="2025-05", params="24B", ctx=32768, out=8192,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.10, pout=0.30, reason=True, tools=True, hf="sarvamai/sarvam-m",
      desc="A Mistral Small fine-tune for ten Indian languages, with a thinking mode.",
      b={},
      verified="2026-08"),
    M("ling-1t", "Ling-1T", "inclusion", rel="2025-10", arch="MoE", params="1T", active="50B",
      ctx=131072, out=32768, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.50, pout=2.0, reason=False, tools=True,
      hf="inclusionAI/Ling-1T",
      desc="A trillion-parameter open non-reasoning model from Ant Group's research arm.",
      b={"aime": 70.4},
      verified="2026-08"),
    M("minicpm4-8b", "MiniCPM4 8B", "openbmb", rel="2025-06", params="8B", ctx=32768, out=8192,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=True,
      pin=0.02, pout=0.05, reason=False, tools=True, hf="openbmb/MiniCPM4-8B",
      desc="Built around sparse attention for fast long-context inference on end devices.",
      b={"mmlu_pro": 45.0},
      verified="2026-08"),
    M("dots-llm1", "dots.llm1", "rednote", rel="2025-06", arch="MoE", params="142B",
      active="14B", ctx=32768, out=8192, inp=["text"], outp=["text"], lic="MIT", open=True,
      hosted_price=True, pin=0.20, pout=0.60, reason=False, tools=True,
      hf="rednote-hilab/dots.llm1.inst",
      desc="Trained on 11.2T tokens with no synthetic data at all — an unusual choice, and "
           "the reason the release drew attention.",
      b={"mmlu_pro": 60.0},
      verified="2026-08"),
    M("openelm-3b", "OpenELM 3B", "apple", rel="2024-04", params="3B", ctx=2048, out=2048,
      inp=["text"], outp=["text"], lic="Apple Sample Code License", open=True,
      hosted_price=True, pin=0.01, pout=0.02, reason=False, tools=False,
      hf="apple/OpenELM-3B-Instruct",
      desc="Apple's open research model, using layer-wise scaling to spend parameters "
           "where they matter most.",
      b={"mmlu_pro": 20.0},
      verified="2026-08"),

    # ------------------------------------------------------------- CorX Labs
    M("corx3-8-27b", "CorX3.8-27B", "corx", rel="2026-08", params="27B", ctx=32768, out=8192,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=False,
      reason=False, tools=True, hf="Sigmandndnns/CorX3.8-27B", local="/models/corx3-8/",
      desc="Jamaica's first large open-weight LLM — a Jamaican Patois-speaking assistant "
           "fine-tuned from Qwen3.8-27B and fully merged.",
      b={},
      verified="2026-08"),
    # Not a language model, so the text benchmarks below do not apply to it and
    # its row is deliberately empty rather than padded. `kind` keeps the index
    # honest about that instead of letting it read as a weak LLM.
    M("tristream-svs", "TriStream-SVS", "corx", rel="2026", params="321.8M",
      kind="Singing voice synthesis",
      arch="3 parallel encoders + late fusion trunk, rectified flow decoder",
      inp=["text", "audio"], outp=["audio"], lic="Apache 2.0", open=True,
      hosted_price=False, reason=False, tools=False,
      hf="Sigmandndnns/TriStream-SVS-300M", local="/models/tristream-svs/",
      desc="A singing voice synthesis model that builds the source-filter theory of the human "
           "voice into its architecture as a hard constraint — pitch, timbre and breath texture "
           "run as three parallel encoder streams, combined only in a late fusion trunk. "
           "Generates at 24 kHz through rectified flow matching in roughly 32 sampling steps.",
      b={},
      verified="2026-09"),
    M("corx1-5", "CorX1.5", "corx", rel="2026-02", params="157.8M", ctx=1024, out=1024,
      inp=["text"], outp=["text"], lic="Apache 2.0", open=True, hosted_price=False,
      reason=False, tools=False, hf="Sigmandndnns/CorX1.5-160M", local="/models/corx1-5/",
      desc="A 158M-parameter decoder-only transformer written and trained from scratch on a "
           "single GPU — architecture, tokenizer, pretraining and fine-tuning.",
      b={},
      verified="2026-08"),
]


# ---------------------------------------------------------------------------
# Curated head-to-heads.
#
# These get their own static, indexable page. "X vs Y" is how people actually
# search, so the pairs are chosen for real decision points — not every possible
# combination, which would be n-squared and mostly noise.
# ---------------------------------------------------------------------------
COMPARISONS = [
    ("gpt-5", "claude-opus-4-5"),
    ("gpt-5", "gemini-3-pro"),
    ("claude-opus-4-5", "gemini-3-pro"),
    ("claude-sonnet-4-5", "gpt-5"),
    ("claude-sonnet-4-5", "gemini-2-5-pro"),
    ("claude-sonnet-4-5", "claude-opus-4-5"),
    ("claude-sonnet-4-5", "claude-haiku-4-5"),
    ("gpt-5", "gpt-5-mini"),
    ("gpt-5-mini", "claude-haiku-4-5"),
    ("gemini-2-5-pro", "gemini-3-pro"),
    ("gemini-2-5-flash", "gpt-5-mini"),
    ("grok-4", "gpt-5"),
    ("grok-4", "claude-opus-4-5"),
    ("deepseek-v3-2", "gpt-5"),
    ("deepseek-v3-2", "claude-sonnet-4-5"),
    ("deepseek-r1", "gpt-5"),
    ("deepseek-r1", "deepseek-v3-2"),
    ("kimi-k2-thinking", "claude-opus-4-5"),
    ("kimi-k2-thinking", "deepseek-v3-2"),
    ("glm-4-6", "claude-sonnet-4-5"),
    ("glm-4-6", "deepseek-v3-2"),
    ("qwen3-235b-a22b", "deepseek-v3-2"),
    ("qwen3-coder-480b", "claude-sonnet-4-5"),
    ("qwen3-coder-480b", "glm-4-6"),
    ("llama-4-maverick", "deepseek-v3"),
    ("llama-4-maverick", "qwen3-235b-a22b"),
    ("llama-3-3-70b", "qwen2-5-72b"),
    ("minimax-m2", "glm-4-6"),
    ("gpt-oss-120b", "deepseek-v3-2"),
    ("gpt-oss-120b", "qwen3-235b-a22b"),
    ("gpt-oss-20b", "qwen3-30b-a3b"),
    ("mistral-medium-3", "gpt-4-1-mini"),
    ("mistral-small-3-2", "gemma-3-27b"),
    ("gemma-3-27b", "qwen3-32b"),
    ("gemma-3-27b", "llama-3-3-70b"),
    ("phi-4", "gemma-3-12b"),
    ("gpt-4o", "claude-3-5-sonnet"),
    ("gpt-4o", "gpt-4-1"),
    ("gpt-4o-mini", "gemini-2-0-flash"),
    ("o3", "gpt-5"),
    ("o4-mini", "gpt-5-mini"),
    ("claude-3-7-sonnet", "claude-sonnet-4-5"),
    ("command-a", "llama-3-3-70b"),
    ("nova-pro", "gpt-4o"),
    ("qwq-32b", "qwen3-32b"),
    ("grok-4-fast", "gemini-2-5-flash"),
    ("gpt-4-1", "gemini-2-5-pro"),
    ("claude-haiku-4-5", "gemini-2-5-flash"),
    ("corx3-8-27b", "gemma-3-27b"),
    ("corx3-8-27b", "qwen3-32b"),
    ("corx3-8-27b", "mistral-small-3-2"),
    ("corx3-8-27b", "qwen2-5-32b"),
    ("corx3-8-27b", "llama-3-3-70b"),
    ("corx3-8-27b", "gpt-oss-20b"),
    ("corx3-8-27b", "corx1-5"),
    ("corx1-5", "llama-3-2-1b"),
    ("corx1-5", "gemma-3-4b"),
    ("claude-opus-5", "claude-opus-4-5"),
    ("claude-sonnet-5", "claude-sonnet-4-5"),
    ("claude-fable-5-1", "claude-opus-5"),
    ("llama-3-1-70b", "llama-3-3-70b"),
    ("qwen3-14b", "gemma-3-12b"),
    ("qwen3-8b", "llama-3-1-8b"),
    ("qwen3-4b", "gemma-3-4b"),
    ("deepseek-r1-distill-32b", "qwq-32b"),
    ("mistral-nemo", "llama-3-1-8b"),
    ("mistral-7b", "qwen2-5-7b"),
    ("grok-code-fast-1", "qwen3-coder-480b"),
    ("nemotron-nano-9b", "qwen3-8b"),
    ("exaone-4-32b", "qwen3-32b"),
    ("gpt-4-turbo", "gpt-4o"),
    ("gemini-1-5-pro", "gemini-2-5-pro"),
    ("gemma-2-27b", "gemma-3-27b"),
    ("phi-4", "qwen3-14b"),
    ("falcon-h1-34b", "qwen3-32b"),
    ("kimi-k2", "kimi-k2-thinking"),
]


# ---------------------------------------------------------------------------
# Derived helpers
# ---------------------------------------------------------------------------
BY_SLUG = {m["slug"]: m for m in MODELS}


def validate():
    """Fail loudly rather than shipping a catalogue that renders wrong."""
    errors = []
    seen = set()
    for m in MODELS:
        s = m["slug"]
        if s in seen:
            errors.append("duplicate slug: " + s)
        seen.add(s)
        if m["company"] not in COMPANIES:
            errors.append("%s: unknown company %r" % (s, m["company"]))
        for k in m.get("b", {}):
            if k not in BENCH_BY_KEY:
                errors.append("%s: unknown benchmark %r" % (s, k))
        for k, v in m.get("b", {}).items():
            if BENCH_BY_KEY[k]["unit"] == "pct" and not (0 <= v <= 100):
                errors.append("%s: %s=%r out of range" % (s, k, v))
        if m.get("ctx") and m.get("out") and m["out"] > m["ctx"]:
            errors.append("%s: max output exceeds context window" % s)
    for a, b in COMPARISONS:
        for s in (a, b):
            if s not in BY_SLUG:
                errors.append("comparison references unknown model: " + s)
        if a == b:
            errors.append("comparison compares a model with itself: " + a)
    if errors:
        raise SystemExit("Catalogue is invalid:\n  " + "\n  ".join(errors))
    return True


if __name__ == "__main__":
    validate()
    print("%d models, %d companies, %d benchmarks, %d comparisons — all valid."
          % (len(MODELS), len(COMPANIES), len(BENCHMARKS), len(COMPARISONS)))
